version: '3'

services:
  postgres:
    build:
       context: .
       dockerfile: docker/postgres/Dockerfile
    image: blog_app_db
    container_name: blog_app_db
    volumes:
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
      - ./tmp/db:/var/lib/postgresql/data
    env_file: docker/postgres/.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 2s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: blog_app_backend
    container_name: blog_app_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
#   nginx:
#     restart: always
#     image: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./docker/nginx/:/etc/nginx/
#       - /static
#     depends_on:
#       - backend