version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: blog_app_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_ENGINE: django.db.backends.postgresql
      DATABASE_DB: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres
    container_name: blog_app_db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/:/etc/nginx/"
      - /static
    depends_on:
      - backend